import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navigation from "./components/navigation";
import HeroImage from "./components/heroImage";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <main className={styles.main}>
          <Head>
            <title>EdApp and Marley Spoon</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navigation />

          <HeroImage />
          <img src="images/marley-spoon-logo.png" alt="Marley Spoon logo" />
          <h1 className={styles.title}>EdApp and Marley Spoon</h1>
          <h2 className={styles.subheading}>A Food Services Case Study</h2>
          <p className={styles.description}>
            This is how Marley Spoon leveraged EdApp to onboard hundreds of new
            employees to support the unprecedented growth brought on by
            COVID-19.
          </p>
        </main>
      </div>

      <main className={styles.main}>
        {/* Text image block, Image LHS, text right */}

        <div className="row">
          <div className={styles.container}>
            <h2 className={styles.subheading}>
              Onboarding hundreds of new team members during COVID-19
            </h2>
            <p>
              Marley Spoon typically onboards new staff with face-to-face
              training, complemented by surveys. Since COVID-19, however, more
              people opted to order fresh ingredients to their doors, which
              resulted in a tremendous surge in demand.
            </p>

            <p>
              As an essential business provider, Marley Spoon was able to hire
              the largest amount of staff in the smallest amount of time on
              record. Since classroom training was no longer a viable option,
              Marley Spoon required a solution that could easily onboard and
              train their hundreds of new team members efficiently and
              effectively.
            </p>
          </div>
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
